### ISSUE TITLE
TypeError: PortfolioAllocation.maximumSharpeRatioWeights is not a function

### ISSUE THREAD

**Issue by digelim** [lequant40/portfolio_allocation_js#4]

**Comment by lequant40** [comment]
Hello @digelim!

Thanks for reporting this.

Would you have more details ? Like, are you trying to call PortfolioAllocation.maximumSharpeRatioWeights from Google Sheets or from a tagged version (like, 0.0.6 or below) or from the currently delivered JavaScript library in this repo ?

If from Google Sheets or a tagged version, this behaviour is normal, as max Sharpe has been introduced only on master for now, and is to be included with version 0.0.7.

Otherwise, would you have some code extract ?

(I really must fall back the updates I made to the README ...)

Cheers,

Roman

**Comment by digelim** [comment]
Hi Roman,

I'm using the npm module. I checked and noticed that the
maximumSharpeRatioWeights function is missing in the dist file, which was
causing the issue (although the github version contains it). Is the npm
version outdated?

Thanks for the amazing library! You rock

**Comment by lequant40** [comment]
Ah, sorry, really my bad: 
* The npm version is the (correct) 0.0.6 version, in which maximumSharpeRatioWeights is not included, despite what the README is currently stating...
* The Github master version is the (future) 0.0.7 version, in which this function is defined, but is not ready yet for publication to npm

So, I will update the README on master to only reference the functions/methods usable on the currently delivered version.

Thanks for reporting.

**Comment by lequant40** [comment]
Solved with todays' delivery of v 0.0.7 of the library !
